### ISSUE TITLE
Support Guzzle 6

### ISSUE THREAD

**Issue by cilefen** [FriendsOfPHP/Goutte#215] opened 2015-05-26 20:35 UTC
Guzzle 6.0.0 was just released https://github.com/guzzle/guzzle/releases

**Comment by vredeling** [comment] 2015-06-15 12:09
Duplicate of https://github.com/laracasts/Integrated/issues/93

**Comment by fabpot** [comment] 2015-06-15 14:49
anyone wanting to make it happen?

**Comment by csarrazi** [comment] 2015-06-17 23:16
Done! Waiting for review :)

**Closed** 2015-06-21 20:35 UTC

**Comment by fabpot** [comment] 2015-06-21 20:37
3.0.0 with Guzzle 6.0 support is out. Thanks @csarrazi!

**Comment by cilefen** [comment] 2015-06-21 21:28
Thank you @csarrazi.

**Comment by csarrazi** [comment] 2015-06-21 21:51
You're welcome! :)
